language: python

services:
  - docker

before_install:
  - docker build -t bambot/bang_central .
  - docker run -d --name bang_central bambot/bang_central 
  - docker ps -a
  - docker stop bang_central
  - docker run bambot/bang_central /bin/sh -c "export environment=test; cd /home/bam/bangcentral; . venv/bin/activate"

script:
  - docker run bambot/bang_central /bin/sh -c "export environment=test; cd /home/bam/bangcentral; . venv/bin/activate &&./manage.py test"

