dist: xenial
language: python
environement:
- ENVIRONMENT=test
- HOST_HTTP_PORT=8000
services:
- docker
script:
- docker-compose run web ./manage.py test
deploy:
- provider: script
  skip_cleanup: true
  script: cd scripts && bash deploy.sh master
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: cd scripts 6& bash deploy.sh stage
  on:
    branch: stage
