dist: xenial
language: python
environement:
- ENVIRONMENT=test
- HOST_HTTP_PORT=8000
services:
- docker
script:
- docker-compose run web ./manage.py test
deploy:
  skip_cleanup: true
- provider: script
  script: bash scripts/deploy.sh master
  on:
    branch: master
- provider: script
  script: bash scripts/deploy.sh stage
  on:
    branch: stage
