version: '3.3'
services:
  web:
    restart: always
    image: twitchbambot/bang_central:master
    volumes: 
     - ./config/nginx:/etc/nginx/conf.d
     - /static:/home/bam/bangcentral/static/
    environment:
     - CLIENT_ID
     - REDIRECT_URI
     - CLIENT_SECRET
     - ENVIRONMENT
     - DJANGO_SECRET_KEY
     - ALLOWED_HOST
     - DB_USER
     - DB_PASSWORD
     - DB_HOST
     - DB_PORT
    networks:
      - nginx_network
    command: gunicorn --bind 0.0.0.0:80 bang_central.wsgi 
  nginx:
    restart: always
    image: nginx:1.13
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - /static:/static/
    depends_on: 
      - web
    environment:
     - SERVER_NAME
    networks:
      - nginx_network
  watchtower:
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --schedule "0 4 1 * *" --cleanup
networks:
  nginx_network:
    driver: bridge
