version: '3.3'
services:
  web:
    restart: always
    build: .
    volumes:
     - .:/home/bam/bangcentral
     - /static:/home/bam/bangcentral/static/
     - ./config/nginx:/etc/nginx/conf.d
    environment:
     - CLIENT_ID
     - CLIENT_SECRET
     - ALLOWED_HOST='*'
     - REDIRECT_URI='http://127.0.0.1:8000/bot/login'
    ports:
      - "8000"
    command: './manage.py runserver 0.0.0.0:8000'
