version: '3.7'
services:
  web:
    image: bang_central
    volumes:
     - .:/home/bam/bangcentral
    environment:
     - CLIENT_ID
     - CLIENT_SECRET
     - ENVIRONMENT
     - DJANGO_SECRET_KEY
     - ALLOWED_HOST
     - DB_USER
     - DB_PASSWORD
     - DB_HOST
     - DB_PORT
    networks:  # <-- here
      - nginx_network
  nginx:
    image: nginx:1.13
    ports:
      - $HOST_HTTP_PORT:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on: 
      - web
    networks:  # <-- here
      - nginx_network
networks:  # <-- and here
  nginx_network:
    driver: bridge
