version: '3.3'
services:
  web:
    restart: always
    image: twitchbambot/bang_central:master
    environment:
     - CLIENT_ID
     - CLIENT_SECRET
     - ENVIRONMENT
     - DJANGO_SECRET_KEY
     - ALLOWED_HOST
     - DB_USER
     - DB_PASSWORD
     - DB_HOST
     - DB_PORT
    networks:  # <-- here
      - nginx_network
    command: gunicorn --bind 0.0.0.0:8000 bang_central.wsgi 
  nginx:
    restart: always
    image: nginx:1.13
    ports:
      - $HOST_HTTP_PORT:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on: 
      - web
    networks:  # <-- here
      - nginx_network
  watchtower:
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --schedule "0 4 1 * *" --cleanup
networks:  # <-- and here
  nginx_network:
    driver: bridge
