# Generated by Django 2.2.3 on 2019-10-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchuser',
            name='command_character',
            field=models.CharField(default='!', max_length=1),
        ),
        migrations.CreateModel(
            name='Blast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('value', models.CharField(max_length=500)),
                ('twitch_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blasts', to='bangs.TwitchUser')),
            ],
        ),
    ]
