# Generated by Django 2.2.3 on 2019-08-09 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bang',
            name='twitch_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bangs.TwitchUser'),
            preserve_default=False,
        ),
    ]
