# Generated by Django 2.2.4 on 2019-08-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangs', '0002_bang_twitch_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bang',
            name='twitch_user',
        ),
    ]
